name: Scheduled Bug Scan

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 2 AM UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  bugscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install tools
        run: |
          sudo apt install -y subfinder
          curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest \
          | grep "browser_download_url.*linux_amd64.zip" \
          | cut -d '"' -f 4 \
          | wget -qi -
          unzip nuclei*.zip
          sudo mv nuclei /usr/local/bin/

      - name: Run Orchestrator
        run: |
          python -m orchestrator.main --scope config/targets.txt
